export const projects = [
  {
    id: 10,
    image: "/projects/das.png",
    title: "DashBoard",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "DashBoard online web-store application",
    code: "#",
    demo: "#",
  },
  {
    id: 13,
    image: "/projects/555.png",
    title: "BrAcademy",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "BrAcademy online web-store application",
    code: "#",
    demo: "#",
  },
  {
    id: 16,
    image: "/projects/2023-06-10.png",
    title: "Garaj113",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "Garaj113 online web-store application",
    code: "#",
    demo: "https://garaj113.ru/",
  },
  {
    id: 10,
    image: "/projects/das.png",
    title: "DashBoard",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "DashBoard online web-store application",
    code: "#",
    demo: "#",
  },
  {
    id: 13,
    image: "/projects/555.png",
    title: "BrAcademy",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "BrAcademy online web-store application",
    code: "#",
    demo: "#",
  },
  {
    id: 16,
    image: "/projects/2023-06-10.png",
    title: "Garaj113",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "Garaj113 online web-store application",
    code: "#",
    demo: "https://garaj113.ru/",
  },
  {
    id: 10,
    image: "/projects/das.png",
    title: "DashBoard",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "DashBoard online web-store application",
    code: "#",
    demo: "#",
  },
  {
    id: 13,
    image: "/projects/555.png",
    title: "BrAcademy",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "BrAcademy online web-store application",
    code: "#",
    demo: "#",
  },
  {
    id: 16,
    image: "/projects/2023-06-10.png",
    title: "Garaj113",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "Garaj113 online web-store application",
    code: "#",
    demo: "https://garaj113.ru/",
  },
  {
    id: 10,
    image: "/projects/das.png",
    title: "DashBoard",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "DashBoard online web-store application",
    code: "#",
    demo: "#",
  },
  {
    id: 13,
    image: "/projects/555.png",
    title: "BrAcademy",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "BrAcademy online web-store application",
    code: "#",
    demo: "#",
  },
  {
    id: 16,
    image: "/projects/2023-06-10.png",
    title: "Garaj113",
    techlogogies: ["React.js", "SCSS", "TypeScript", "React-Router-Dom"],
    description: "Garaj113 online web-store application",
    code: "#",
    demo: "https://garaj113.ru/",
  },
];
